### ISSUE TITLE
Show preview in index pages

### ISSUE THREAD

**Issue by rosendi** [Dreamersoul/administrate-field-active_storage#16]
Is it possible to show actual preview in index pages? By default it renders:

<img width="235" alt="Screenshot 2019-06-04 at 00 11 11" src="https://user-images.githubusercontent.com/803388/58834954-4b01cb00-865d-11e9-8c5f-909d842de6ec.png">

And how could I resize preview in show page? I found [this `options`](https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/lib/administrate/field/active_storage.rb#L37), but don't understand how I could pass the options.

**Comment by Dreamersoul** [comment]
1. That is an option but I thought it looked too much to be on the index page if you have a rough estimate on how it should look like please share it and I'll implement it 

2. I could add an option to specify the maximum height for images if that's what you need

**Comment by rosendi** [comment]
1. If the index page is an index of photos then showing previews is the only way in order to find a proper photo.

2. I think we can add something like `preview_options` and pass it to the preview method, so users decide how ActiveStorage should process the preview:

```
def preview(attachment, options <--- What's this? Where it comes from?)
  Rails.application.routes.url_helpers.rails_representation_path(attachment.preview(options.fetch(:preview_options,{})), only_path: true)
end
```

**Comment by Dreamersoul** [comment]
1. alright ill probably add an option to allow people to show previews in index pages as thumbnails, but only for ```has_one``` since if an object has 100 images that would be a mess tbh

2. this comes from the view file check this: https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/app/views/fields/active_storage/_item.html.erb#L32

check where it says resize those are the preview options, how about i let the developer pass a custom resize to allow you to resize to the size you want?

**Comment by Dreamersoul** [comment]
Please feel free to reopen if I missed something

**Comment by deltapurna** [comment]
hi bro Hamad @Dreamersoul , I found an issue with the release `0.1.7`. Created a pull request #18 to fix it. Let me know if it make sense.
