### ISSUE TITLE
Why do we need to explicitly setup a destroy url?

### ISSUE THREAD

**Issue by iamnader** [Dreamersoul/administrate-field-active_storage#54]
This commit gets rid of the default behavior: https://github.com/Dreamersoul/administrate-field-active_storage/commit/9e2f2eb31b13d3891e4830139b32605855775df3

**Comment by Dreamersoul** [comment]
The previous way had a bug that effected a couple of users (#38 #39) so as a quick fix I reverted the method back to what it was which was retrieving the destroy URL from the options passed.

I remember looking into a way to set a default empty destroy URL and preventing the bugs shown in #38 and #39. However due to the lack of time I didn't get around to it.
If you have a better way of doing this I will be happy to merge a PR.  👍🏻

**Comment by Dreamersoul** [comment]
closed for inactivity
